name: micro_panda
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/panda-io/micro-panda-dart

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  test: ^1.29.0

dev_dependencies:
  lints: ^6.0.0
